<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{AssignmentController,AuthController,DashboardController,MaterialController,NotificationController,PerformanceController,ProfileController,SupervisionController,TeachingReportController,TimetableController,UserController};

Route::redirect('/','/login');
Route::middleware('guest')->group(function(){Route::get('/login',[AuthController::class,'create'])->name('login');Route::post('/login',[AuthController::class,'store'])->name('login.store');});
Route::middleware('auth')->group(function(){
 Route::post('/logout',[AuthController::class,'destroy'])->name('logout');
 foreach(['admin','school_manager','teacher','supervisor'] as $role){$prefix=$role==='school_manager'?'manager':$role;Route::get("/$prefix/dashboard",[DashboardController::class,'show'])->middleware("role:$role")->name("$role.dashboard");}
 Route::get('/materials',[MaterialController::class,'index'])->name('materials.index');Route::get('/materials/{material}',[MaterialController::class,'show'])->name('materials.show');Route::get('/materials/{material}/download',[MaterialController::class,'download'])->name('materials.download');
 Route::get('/reports',[TeachingReportController::class,'index'])->name('reports.index');Route::get('/reports/{report}',[TeachingReportController::class,'show'])->name('reports.show');Route::get('/reports/{report}/download',[TeachingReportController::class,'download'])->name('reports.download');
 Route::middleware('role:teacher')->group(function(){Route::get('/teacher/timetable',[TimetableController::class,'index'])->name('teacher.timetable');Route::get('/teacher/reports/create',[TeachingReportController::class,'create'])->name('teacher.reports.create');Route::post('/teacher/reports',[TeachingReportController::class,'store'])->name('teacher.reports.store');});
 Route::middleware('role:admin')->prefix('admin')->name('admin.')->group(function(){Route::resource('users',UserController::class)->except('show');Route::patch('users/{user}/toggle',[UserController::class,'toggle'])->name('users.toggle');Route::resource('timetables',TimetableController::class)->except('show');Route::get('assignments',[AssignmentController::class,'edit'])->name('assignments.edit');Route::post('assignments',[AssignmentController::class,'update'])->name('assignments.update');Route::get('materials/create',[MaterialController::class,'create'])->name('materials.create');Route::post('materials',[MaterialController::class,'store'])->name('materials.store');Route::delete('materials/{material}',[MaterialController::class,'destroy'])->name('materials.destroy');});
 Route::middleware('role:supervisor')->prefix('supervisor')->name('supervisor.')->group(function(){Route::get('teachers',[SupervisionController::class,'teachers'])->name('teachers.index');Route::get('teachers/{teacher}',[SupervisionController::class,'teacher'])->name('teachers.show');Route::get('teachers/{teacher}/feedback',[SupervisionController::class,'feedbackForm'])->name('feedback.create');Route::post('teachers/{teacher}/feedback',[SupervisionController::class,'feedback'])->name('feedback.store');Route::get('teachers/{teacher}/evaluation',[SupervisionController::class,'evaluationForm'])->name('evaluation.create');Route::post('teachers/{teacher}/evaluation',[SupervisionController::class,'evaluation'])->name('evaluation.store');});
 Route::middleware('role:admin,school_manager')->group(function(){Route::get('/performance',[PerformanceController::class,'index'])->name('performance.index');Route::get('/performance/create',[PerformanceController::class,'create'])->name('performance.create');Route::post('/performance',[PerformanceController::class,'store'])->name('performance.store');Route::get('/performance/{report}',[PerformanceController::class,'show'])->name('performance.show');Route::get('/performance/{report}/download',[PerformanceController::class,'download'])->name('performance.download');});
 Route::get('/notifications',[NotificationController::class,'index'])->name('notifications.index');Route::post('/notifications/read-all',[NotificationController::class,'readAll'])->name('notifications.read-all');Route::post('/notifications/{id}/read',[NotificationController::class,'read'])->name('notifications.read');
 Route::get('/profile',[ProfileController::class,'edit'])->name('profile.edit');Route::patch('/profile',[ProfileController::class,'update'])->name('profile.update');Route::put('/profile/password',[ProfileController::class,'password'])->name('profile.password');
});
