<?php
namespace Tests\Feature;
use App\Models\{Evaluation,Feedback,TeachingReport,User};use App\Notifications\AfhmNotification;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\Notification;use Tests\TestCase;
class AfhmWorkflowTest extends TestCase { use RefreshDatabase;
 private function user(string $role='teacher',array $extra=[]):User{return User::factory()->role($role)->create($extra);}
 public function test_authentication_redirect_logout_and_inactive_account():void{$admin=$this->user('admin',['email'=>'a@test.com']);$this->post('/login',['email'=>'a@test.com','password'=>'password'])->assertRedirect(route('admin.dashboard'));$this->post('/logout')->assertRedirect(route('login'));$inactive=$this->user('teacher',['email'=>'off@test.com','is_active'=>false]);$this->post('/login',['email'=>$inactive->email,'password'=>'password'])->assertSessionHasErrors('email');$this->assertGuest();$this->post('/login',['email'=>$admin->email,'password'=>'wrong'])->assertSessionHasErrors('email');}
 public function test_role_authorization_protects_resources():void{$teacher=$this->user();$supervisor=$this->user('supervisor');$other=$this->user();$this->actingAs($teacher)->get('/admin/users')->assertForbidden();$this->actingAs($teacher)->get('/admin/timetables')->assertForbidden();$this->actingAs($supervisor)->post(route('supervisor.evaluation.store',$other),['score'=>4,'comments'=>'Good'])->assertForbidden();}
 public function test_admin_user_workflow_and_uniqueness():void{$admin=$this->user('admin');$data=['name'=>'New Teacher','email'=>'new@test.com','phone'=>'+21890001','role'=>'teacher','password'=>'password','password_confirmation'=>'password'];$this->actingAs($admin)->post(route('admin.users.store'),$data)->assertRedirect(route('admin.users.index'));$u=User::whereEmail('new@test.com')->firstOrFail();$this->actingAs($admin)->patch(route('admin.users.toggle',$u))->assertSessionHas('success');$this->assertFalse($u->fresh()->is_active);$this->actingAs($admin)->post(route('admin.users.store'),$data)->assertSessionHasErrors(['email','phone']);}
 public function test_timetable_conflicts_and_teacher_read_only_access():void{$admin=$this->user('admin');$teacher=$this->user();$base=['teacher_id'=>$teacher->id,'day'=>'Mon','start_time'=>'08:00','end_time'=>'09:00','classroom'=>'A1','subject'=>'Grammar'];$this->actingAs($admin)->post(route('admin.timetables.store'),$base)->assertSessionHas('success');$overlap=$base;$overlap['start_time']='08:30';$overlap['end_time']='09:30';$this->actingAs($admin)->post(route('admin.timetables.store'),$overlap)->assertSessionHasErrors('start_time');$this->actingAs($teacher)->get(route('teacher.timetable'))->assertOk();$this->actingAs($teacher)->post(route('admin.timetables.store'),$base)->assertForbidden();}
 public function test_assignment_report_feedback_and_evaluation_workflows():void{Notification::fake();$admin=$this->user('admin');$supervisor=$this->user('supervisor');$teacher=$this->user();$this->actingAs($admin)->post(route('admin.assignments.update'),['teacher_id'=>$teacher->id,'supervisor_id'=>$supervisor->id])->assertSessionHas('success');$this->assertEquals($supervisor->id,$teacher->fresh()->supervisor_id);Notification::assertSentTo($supervisor,AfhmNotification::class);$this->actingAs($teacher)->post(route('teacher.reports.store'),['report_type'=>'weekly','title'=>'Weekly progress','content'=>'Completed the unit objectives.'])->assertRedirect();Notification::assertSentTo($supervisor,AfhmNotification::class);$this->actingAs($supervisor)->post(route('supervisor.feedback.store',$teacher),['rating'=>5,'content'=>'Excellent progress.'])->assertSessionHas('success');$this->actingAs($supervisor)->post(route('supervisor.evaluation.store',$teacher),['score'=>4.5,'comments'=>'Well prepared lesson.'])->assertSessionHas('success');$this->assertDatabaseHas('feedbacks',['teacher_id'=>$teacher->id,'rating'=>5]);$this->assertDatabaseHas('evaluations',['teacher_id'=>$teacher->id]);}
 public function test_performance_generation_uses_stored_data():void{$manager=$this->user('school_manager');$supervisor=$this->user('supervisor');$teacher=$this->user('teacher',['supervisor_id'=>$supervisor->id]);TeachingReport::create(['teacher_id'=>$teacher->id,'title'=>'Progress','content'=>'Data','report_type'=>'weekly','submitted_at'=>now()]);Evaluation::create(['supervisor_id'=>$supervisor->id,'teacher_id'=>$teacher->id,'score'=>4.5,'comments'=>'Strong','evaluated_at'=>now()]);Feedback::create(['supervisor_id'=>$supervisor->id,'teacher_id'=>$teacher->id,'rating'=>4,'content'=>'Good','submitted_at'=>now()]);$this->actingAs($manager)->post(route('performance.store'),['title'=>'August report','period'=>'August','teacher_id'=>$teacher->id])->assertRedirect();$this->assertDatabaseHas('performance_reports',['generated_by'=>$manager->id]);}
}
